name: Release Build

# Perform optimized/release builds, create a release, and attach build
# artifacts to the release when a version tag is pushed.
#
# The tag needs to be pushed by name, as `git push --tags` to push all
# tags does not appear to trigger the action.
#
# The versioned release process is similar to the following:
# 1. Add an annotated tag with the release version string.
#        git tag -a v0.9.2
# 2. Draft a message for the annotated tag that is similar to the
#    following. The body of this message will serve as the body of the
#    release message that is specified when the release is created.
#        Release v0.9.2
#
#        Release Highlights
#        - Brief description of new item 1.
#        - Brief description of new item 2.
# 3. Push the tag to GitHub.
#        git push origin v0.9.2

on:
  push:
    tags:
      - v*

jobs:
  linux:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu GCC Release",
            os: ubuntu-18.04,
            artifact: "gfxreconstruct-ubuntu-gcc-release",
            cc: "gcc", cxx: "g++"
          }
    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-xcb-dev libxcb-keysyms1-dev libwayland-dev libxrandr-dev liblz4-dev libzstd-dev
    - name: Run build script
      run: |
        python3 scripts/build.py --skip-check-code-style --skip-tests
    - name: Prepare artifacts
      run: |
        cp LICENSE.txt build/linux/x64/output/bin/
        cp LICENSE_ThirdParty.txt build/linux/x64/output/bin/
        cp USAGE_desktop_Vulkan.md build/linux/x64/output/bin/
        cp layer/vk_layer_settings.txt build/linux/x64/output/bin/
        mv build/linux/x64/output/bin gfxreconstruct-dev
        mv build/linux/x64/output/lib*/*.so gfxreconstruct-dev/
        mv build/linux/x64/output/share/vulkan/explicit_layer.d/*.json gfxreconstruct-dev/
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-dev

  release:
    name: Create Release for Tag
    runs-on: ubuntu-latest
    needs: [ linux ]
    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Get tag body
      id: get_tag_body
      run: |
        # Retrieve the body of the annotated tag's multi-line message and convert it to
        # JSON, as an array of strings, with each line of the message as an array element.
        tag_name=`echo "${{ github.ref }}" | cut -d "/" -f 3`
        tag_body=`git tag -l --format='%(body)' "$tag_name"`
        tag_body_json="["
        while read -r line ; do tag_body_json+="\"${line}\"," ; done < <(echo "$tag_body")
        tag_body_json="${tag_body_json::-1}]" # Replace the trailing ',' with ']'
        echo "::set-output name=tag_body_json::$tag_body_json"
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: "${{ join(fromJson(steps.get_tag_body.outputs.tag_body_json), '\n') }}"
        draft: false
        prerelease: false
    - name: Get release URL
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./release_url
    - name: Upload release URL
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: ./release_url

  publish:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: release
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Upload Ubuntu Release Artifact",
            os: ubuntu-latest,
            artifact: "gfxreconstruct-ubuntu-gcc-release",
            command: "tar czf",
            suffix: "ubuntu-gcc.tar.gz",
            type: "application/x-gtar"
          }
    steps:
    - name: Get tag name
      id: get_tag_name
      run: |
        tag_name=`echo "${{ github.ref }}" | cut -d "/" -f 3`
        echo "::set-output name=tag_name::$tag_name"
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}
    - name: Make release artifacts
      run: |
        ${{ matrix.config.command }} gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}-${{ matrix.config.suffix }} gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}
    - name: Download release URL
      uses: actions/download-artifact@v1
      with:
        name: release_url
        path: ./
    - name: Set upload URL
      id: set_upload_url
      run: |
        upload_url=`cat ./release_url`
        echo "::set-output name=upload_url::$upload_url"
    - name: Upload release artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_name: gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}-${{ matrix.config.suffix }}
        asset_path: ./gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}-${{ matrix.config.suffix }}
        asset_content_type: ${{ matrix.config.type }}
